# fly.toml app configuration file generated for aquaquartz on 2024-02-29T13:04:26-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aquaquartz'
primary_region = 'den'

[build]
  image = 'remremegg/aquaquartz:latest'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[services]]
  internal_port = 443
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']
  [[services.ports]]
    port = 443
    force_https = false
    handlers = ["tls"]